[window]
# Window dimensions (change if needed)
dimensions = { columns = 100, lines = 30 }
padding = { x = 10, y = 10 }
opacity = 1.0
startup_mode = "Windowed"

# Font configuration
[font]
size = 9.0
offset = { x = 0, y = 0 }
glyph_offset = { x = 0, y = 0 }

# Colors (Gruvbox)
[colors]
primary = { background = "#282828", foreground = "#ebdbb2" }

cursor = { text = "#282828", cursor = "#ebdbb2" }

[colors.normal]
black = "#282828"
red = "#cc241d"
green = "#98971a"
yellow = "#d79921"
blue = "#458588"
magenta = "#b16286"
cyan = "#689d6a"
white = "#a89984"

[colors.bright]
black = "#928374"
red = "#fb4934"
green = "#b8bb26"
yellow = "#fabd2f"
blue = "#83a598"
magenta = "#d3869b"
cyan = "#8ec07c"
white = "#ebdbb2"
